workflow:
  name: demo
  context:
    key1: value1
    key2: value2
  effects:
    - name: effect1
      class: effects.print.Print
      config:
        value: Hello,
    - name: effect2
      class: effects.print.Print
      config:
        value: World!
