workflow:
  name: demo
  context:
    key1: value1
    key2: value2
  effects:
    - name: print_hello
      class: effects.print.Print
      config:
        value:
          default: Hello,
          context: null
    - name: sleep_5
      class: effects.sleep.Sleep
      config:
        seconds:
          default: 5
          context: null
    - name: print_world
      class: effects.print.Print
      config:
        value:
          default: World!
          context: null
    - name: list_files
      class: effects.list_files.ListFiles
      config:
        path:
          default: /Users/jxan/Documents/development/effect-flow/effects/*.py
          context: null
    - name: print_files
      class: effects.print.Print
      config:
        value:
          default: "No Files!"
          context: list_files.files
